### ISSUE TITLE
Update docs to be explicitly clear that CmfMenuBundle must come after KnpMenuBundle in AppKernel

### ISSUE THREAD

**Issue by benglass** [symfony-cmf/menu-bundle#252] opened 2016-05-07 03:27 UTC
The docs do show this bundle being registered AFTER KnpMenuBundle however they dont make it explicitly clear that the bundle actually wont work properly unless KnpMenuBundle comes first. This is because the DecorateMenuFactoryPass simply returns if it can't find the knp menu factory.

https://github.com/symfony-cmf/menu-bundle/blob/master/DependencyInjection/Compiler/DecorateMenuFactoryPass.php#L28

Is this the right behavior? It seems like a loud failure might be better. When would it be allowed to use CmfMenuBundle without KnpMenuBundle?

http://symfony.com/doc/current/cmf/bundles/menu/introduction.html

```
As the bundle is using the KnpMenuBundle, you need to instantiate that bundles in addition to the CmfMenuBundle:
```

**Comment by WouterJ** [comment] 2016-05-07 08:58
The bundle system works like this on `Kernel::boot()`:

 1. First, all bundles are initialized
 2. Then, the container is build (if not available in cache)
 3. In this build, a compiler pass executes all DI extensions to load all services
 4. Custom DI extensions (like `DecorateMenuFactoryPass`) are run after that

This means that all services will be available at the time the `DecorateMenuFactoryPass` is executed. I can't see why it has to be initialized before the CmfMenuBundle.

**Comment by benglass** [comment] 2016-05-07 12:52
@WouterJ I see what you mean however before I switched the order of these bundles in AppKernel the behavior of knp_menu_render in twig templates was that it printed <span> tags for most of the Phpcr documents in the menu. I checked the MenuFactory and found that the ContentExtension was missing. I then swapped the order of knp menu bundle so it was first and it fixed the issue and this was the only change I made.

**Comment by WouterJ** [comment] 2016-05-07 12:53
This is probably the same problem as https://github.com/symfony-cmf/menu-bundle/issues/249

**Comment by benglass** [comment] 2016-05-07 12:55
@WouterJ I agree this seems to be the same problem

**Comment by dbu** [comment] 2016-05-09 06:45
indeed, sounds a lot like it. closing this as duplicate of #249

**Closed by dbu** 2016-05-09 06:45 UTC
Labels: unconfirmed
